"""empty message

Revision ID: e0ee829a7e89
Revises: 
Create Date: 2018-09-25 09:32:56.507153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ee829a7e89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cur_From', sa.String(), nullable=False),
    sa.Column('cur_To', sa.String(), nullable=False),
    sa.Column('cur_Rate', sa.Float(), nullable=False),
    sa.Column('cur_avg_Rate', sa.Float(), nullable=False),
    sa.Column('cur_Date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('masukan_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cur_From', sa.String(), nullable=False),
    sa.Column('cur_To', sa.String(), nullable=False),
    sa.Column('cur_Rate', sa.Float(), nullable=False),
    sa.Column('cur_Date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('masukan_rate')
    op.drop_table('exchange_rate')
    # ### end Alembic commands ###
